### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by tyanrv** [BotMill/fb-botmill#118]
Hello, i'm new in programming, so sorry maybe for this question.
So i have did first 2 steps of Creating your Bot Definition, but on the third step when i create MyBotClass, i can't find in dependencies those classes: MessengerProfileApi, PersistentMenu, CallToActionNested, theServices, MessengerProfileApi. 
(version - 2.0.0-RC1)

**Comment by tyanrv** [comment]
ok, i work with version-1.2.1 and it's ok. But i have one more question how can i get messageid for incoming/delivered messages when i get Event?

**Comment by aurasphere** [comment]
Hi tyanrv, sorry for the late reply but I've been really busy lately. 

In order to retrieve the incoming/delivered message IDs, you will have to register for Facebook message_echoes and message_deliveries callback. Once you have done that, for each message you send, you will get back an echo message and a delivery message inside the MessageEnvelope object and both of this will contain the message id (mids field).

**Comment by tyanrv** [comment]
Hi, that's ok. Yeah, you right, thanks for your help, we can close this issue.
