### ISSUE TITLE
Introduce a SparkJava context

### ISSUE THREAD

**Issue by alvin-reyes** [BotMill/fb-botmill#26]
We need to introduce a SparkJava context to handle the get and post callbacks. This will be an alternative for developers that doesn't want to use web.xml/xml or servlet configuration.

**Comment by aurasphere** [comment]
I've looked into this and I'm thinking that this would not apport any real enhancement on the framework. Here's why:

-in order to add a SparkJava app (not embedded on a Jetty server) you need to add this to the web.xml:

`<filter>
    <filter-name>SparkFilter</filter-name>
    <filter-class>spark.servlet.SparkFilter</filter-class>
    <init-param>
        <param-name>applicationClass</param-name>
        <param-value>com.company.YourApplication</param-value>
    </init-param>
</filter>

<filter-mapping>
    <filter-name>SparkFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>` 

so you will still need a web.xml that's actually more complex than the default servlet configuration.
- using Fb-BotMill servlet configuration doesn't exclude the possibility of also adding a SparkJava app if the user does want to.
- implementing a SparkJava would require introducing a new way of loading the bot definitions, since it can't be read from the web.xml AFAIK.

This is the same for Spring Boot. I think that the strength of both of these frameworks is that they let you quickly deploy your app using a main class, but since here we are working with webhooks, you probably don't need it and you will almost always use a web service with an exposed IP. This is my opinion though and I'm open to other point of views. Until then, I'm marking this and Spring Boot as won't fix.
