### ISSUE TITLE
Bot for multiple facebook pages

### ISSUE THREAD

**Issue by r-kat** [BotMill/fb-botmill#73]
I would like to have my bot embedded on multiple Facebook pages. Is there a way to create FbBotMillContext based on PageToken or better way to handle this scenario?

**Comment by alvin-reyes** [comment]
FbBotMill doesn't have this capability right now since we only save a single pageToken for each bot. It would be a great feature to have though. We will put this on our backlog.

If you're curious as to how can you do this:

1. You can change the FbBotMillContext and add a new method that can accept multiple page tokens (you can't put multiple webhook validation tokens as per facebook guidelines).
2. fbPageToken from AbstractFbBot is actually just picking up the token from the properties file, you can introduce a new property with comma delimited (encrypted) page tokens and split() it to make an array
3. Assign this array to the new setup method
4. On NetworkUtils.java - make sure to loop through the available page tokens and call the url for each page token. Right now it only submits a single https call but if we need to support multiple page tokens, we need to loop through the tokens and submit https for each.

We can implement this for you but you may need to wait for us to further evaluate the solution and the designated release.

Thank you for this btw. :)

**Comment by alvin-reyes** [comment]
After some research, this is not possible in our setup right now. We created the framework with the mindset that there will only be one bot for each page. A major change is required for us to implement.

**Comment by r-kat** [comment]
Thank you for your input.
